### ISSUE TITLE
May I ask whether this data set is used for the training of the segmentation task or for the training of the tracking task?

### ISSUE THREAD

**Issue by imzhangyd** [ChristophReich1996/TYC-Dataset#1]
May I ask whether this data set is used for the training of the segmentation task or for the training of the tracking task? Dose this dataset have tracks annotations?

**Comment by ChristophReich1996** [comment]
Hi @imzhangyd, thanks for your interest in our TYC dataset. We only provide ground truth annotations for the task of segmentation. However, we also provide curated TLFM sequences to facilitate the (unsupervised) understanding of cell motions. I hope this helps :)
